# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bigram <- function(strings) {
    .Call('_strmatch_bigram', PACKAGE = 'strmatch', strings)
}

count_sentencesCpp <- function(sentence) {
    .Call('_strmatch_count_sentencesCpp', PACKAGE = 'strmatch', sentence)
}

damerau_levenshtein <- function(A, B) {
    .Call('_strmatch_damerau_levenshtein', PACKAGE = 'strmatch', A, B)
}

damerau_levenshtein_ratio <- function(s1, s2) {
    .Call('_strmatch_damerau_levenshtein_ratio', PACKAGE = 'strmatch', s1, s2)
}

#' Calculate for each string the normalized Damerau-Levenshtein Distance given a set of target strings.
#'
#' @param strings String Vector.
#' @param targets String Vector.
#' @export
most_similar_DL <- function(strings, targets) {
    .Call('_strmatch_most_similar_DL', PACKAGE = 'strmatch', strings, targets)
}

#' Find the max indices given a list of edit distances.
#'
#' Function is designed to find the max indices in a list of numeric vectors.
#' The numeric vectors consist of edit distances, numeric values.
#'
#' @param list_of_edit_distances A list of numeric vectors.
#' @return Integer Vector
#' @export
#'
idx_lookup <- function(list_of_edit_distances) {
    .Call('_strmatch_idx_lookup', PACKAGE = 'strmatch', list_of_edit_distances)
}

jaro_distance <- function(s1, s2) {
    .Call('_strmatch_jaro_distance', PACKAGE = 'strmatch', s1, s2)
}

#' Calculate for each string the Jaro Distance given a set of target strings.
#'
#' @param strings String Vector.
#' @param targets String Vector.
#' @export
most_similar_jaro <- function(strings, targets) {
    .Call('_strmatch_most_similar_jaro', PACKAGE = 'strmatch', strings, targets)
}

jaro_winkler_distance <- function(str1, str2) {
    .Call('_strmatch_jaro_winkler_distance', PACKAGE = 'strmatch', str1, str2)
}

#' Calculate for each string the Jaro Winkler Distance given a set of target strings.
#'
#' @param strings String Vector.
#' @param targets String Vector.
#' @export
most_similar_jw <- function(strings, targets) {
    .Call('_strmatch_most_similar_jw', PACKAGE = 'strmatch', strings, targets)
}

levenstein_distance <- function(s1, s2) {
    .Call('_strmatch_levenstein_distance', PACKAGE = 'strmatch', s1, s2)
}

levenstein_ratio <- function(s1, s2) {
    .Call('_strmatch_levenstein_ratio', PACKAGE = 'strmatch', s1, s2)
}

#' Calculate for each string the normalized Levenstein Distance given a set of target strings.
#'
#' @param strings String Vector.
#' @param targets String Vector.
#' @export
most_similar_levenstein <- function(strings, targets) {
    .Call('_strmatch_most_similar_levenstein', PACKAGE = 'strmatch', strings, targets)
}

read_text <- function(path) {
    .Call('_strmatch_read_text', PACKAGE = 'strmatch', path)
}

cpp_str_sort <- function(strings) {
    .Call('_strmatch_cpp_str_sort', PACKAGE = 'strmatch', strings)
}

read_dictionary <- function() {
    .Call('_strmatch_read_dictionary', PACKAGE = 'strmatch')
}

to_uppercase <- function(str) {
    .Call('_strmatch_to_uppercase', PACKAGE = 'strmatch', str)
}

to_lowercase <- function(str) {
    .Call('_strmatch_to_lowercase', PACKAGE = 'strmatch', str)
}

