# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jaro <- function(s1, s2) {
    .Call('_strmatch_jaro', PACKAGE = 'strmatch', s1, s2)
}

jaro_winkler_distance <- function(str1, str2) {
    .Call('_strmatch_jaro_winkler_distance', PACKAGE = 'strmatch', str1, str2)
}

levenstein_distance <- function(s1, s2) {
    .Call('_strmatch_levenstein_distance', PACKAGE = 'strmatch', s1, s2)
}

levenstein_ratio <- function(s1, s2) {
    .Call('_strmatch_levenstein_ratio', PACKAGE = 'strmatch', s1, s2)
}

to_uppercase <- function(str) {
    .Call('_strmatch_to_uppercase', PACKAGE = 'strmatch', str)
}

to_lowercase <- function(str) {
    .Call('_strmatch_to_lowercase', PACKAGE = 'strmatch', str)
}

